Repository sou-so/Souso-Server, pull requests merged in 2022-12, with the labels that each got.

#124 merge(#113): 프로필 정보 조회 API 반환값 추가
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/response/QueryMyProfileResponse.java
  src/main/java/kr/co/souso/souso/domain/user/service/QueryMyProfileService.java
Labels: feature

#128 merge(#127): TimeZone을 Asia/Seoul로 설정
  Dockerfile
  src/main/java/kr/co/souso/souso/global/date/DateTimeZoneConfiguration.java
  src/main/resources/application.yml
Labels: feature

#130 merge(#129): 북마크 조회 안되는 오류 수정
  src/main/java/kr/co/souso/souso/domain/feed/domain/repository/FeedRepositoryImpl.java
  src/main/java/kr/co/souso/souso/domain/user/service/QueryMyBookmarksPagesService.java
Labels: fix

#132 merge(#131): FeedViewCount 예외 문구 변경
  src/main/java/kr/co/souso/souso/domain/category/service/QueryFeedCategoryPagesService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/DeleteFeedService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/QueryFeedDetailsService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/QueryFeedPagesService.java
  src/main/java/kr/co/souso/souso/domain/user/service/QueryMyBookmarksPagesService.java
  src/main/java/kr/co/souso/souso/domain/user/service/QueryMyFeedPagesService.java
  src/main/java/kr/co/souso/souso/domain/viewcount/exception/FeedViewCountNotFoundException.java
  src/main/java/kr/co/souso/souso/global/error/exception/GlobalErrorCode.java
Labels: fix

#134 merge(#133): 문자 인증 중복 요청 제한
  src/main/java/kr/co/souso/souso/domain/auth/service/CheckAuthCodeExistsService.java
  src/main/java/kr/co/souso/souso/domain/user/exception/AlreadyAuthCodeExistException.java
  src/main/java/kr/co/souso/souso/domain/user/service/UserAuthCodeService.java
  src/main/java/kr/co/souso/souso/global/error/exception/GlobalErrorCode.java
Labels: fix

#136 merge(#135): Redis Transaction 허용 설정
  src/main/java/kr/co/souso/souso/global/redis/RedisConfig.java
Labels: bug, fix

#139 merge(#138): 문자 인증 코드 변경
  README.md
  src/main/java/kr/co/souso/souso/domain/user/service/UserAuthCodeService.java
Labels: fix

#140 merge(#135): rollback
  src/main/java/kr/co/souso/souso/global/redis/RedisConfig.java
Labels: bug, fix

#142 merge(#141): 유저 정보 수정 API formdata로 수정하도록 변경
  src/main/java/kr/co/souso/souso/domain/auth/presentation/dto/request/UserSignInRequest.java
  src/main/java/kr/co/souso/souso/domain/feed/domain/repository/FeedRepositoryCustom.java
  src/main/java/kr/co/souso/souso/domain/feed/domain/repository/FeedRepositoryImpl.java
  src/main/java/kr/co/souso/souso/domain/user/domain/User.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/UserController.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/kr/co/souso/souso/domain/user/service/UpdateUserInfoService.java
  src/main/java/kr/co/souso/souso/global/utils/code/PagingSupportUtil.java
Labels: bug, fix

#144 merge(#143): 게시글 삭제 쿼리 순서 수정
  src/main/java/kr/co/souso/souso/domain/bookmark/domain/repository/FeedBookmarkRepository.java
  src/main/java/kr/co/souso/souso/domain/comment/domain/repository/CommentRepository.java
  src/main/java/kr/co/souso/souso/domain/comment/service/CreateCommentService.java
  src/main/java/kr/co/souso/souso/domain/comment/service/CreateReplyService.java
  src/main/java/kr/co/souso/souso/domain/comment/service/DeleteCommentService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/AddBookmarkService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/AddLikeService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/DeleteFeedService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/SubBookmarkService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/SubLikeService.java
  src/main/java/kr/co/souso/souso/domain/like/domain/repository/FeedLikeRepository.java
  src/main/java/kr/co/souso/souso/domain/meeting/domain/repository/MeetingRepository.java
  src/main/java/kr/co/souso/souso/domain/meeting/service/CreateMeetingService.java
  src/main/java/kr/co/souso/souso/domain/user/domain/User.java
  src/main/java/kr/co/souso/souso/domain/user/service/QueryMyProfileService.java
Labels: bug, fix

#147 merge(#145): 기본 프로필이미지 주소 변경
  src/main/java/kr/co/souso/souso/infrastructure/image/DefaultImage.java
Labels: fix

#149 merge(#148): 비밀번호 정규식 변경
  src/main/java/kr/co/souso/souso/domain/auth/presentation/dto/request/UserSignInRequest.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UpdatePasswordRequest.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UserSignUpRequest.java
Labels: fix

#151 merge(#150): 비밀번호 Regex 변경에 따른 API 문서 Swagger example 변경 및 메시지 구체적으로 변경
  src/main/java/kr/co/souso/souso/domain/auth/presentation/dto/request/UserSignInRequest.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UpdatePasswordRequest.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UserSignUpRequest.java
Labels: fix

#155 merge(#154): 문자 인증 재발송 시간 3분으로 변경
  src/main/java/kr/co/souso/souso/domain/user/domain/UserAuthCode.java
Labels: fix

#157 merge(#156): 댓글 작성자 여부 확인 쿼리 수정
  src/main/java/kr/co/souso/souso/domain/comment/domain/repository/CommentRepositoryImpl.java
Labels: fix

#159 merge(#158): 비밀번호 정규식 수정
  src/main/java/kr/co/souso/souso/domain/auth/presentation/dto/request/UserSignInRequest.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UpdatePasswordRequest.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UserSignUpRequest.java
Labels: fix

#153 merge(#152): 유저 프로필 기본 이미지 변경 추가
  src/main/java/kr/co/souso/souso/domain/user/domain/User.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/kr/co/souso/souso/domain/user/service/UpdateUserInfoService.java
Labels: fix

#161 merge(#160): 일괄 삭제를 위한 OneToMany 연결
  src/main/java/kr/co/souso/souso/domain/bookmark/domain/repository/FeedBookmarkRepository.java
  src/main/java/kr/co/souso/souso/domain/category/domain/repository/FeedCategoryRepository.java
  src/main/java/kr/co/souso/souso/domain/comment/domain/repository/CommentRepository.java
  src/main/java/kr/co/souso/souso/domain/feed/domain/Feed.java
  src/main/java/kr/co/souso/souso/domain/feed/service/DeleteFeedService.java
  src/main/java/kr/co/souso/souso/domain/like/domain/repository/FeedLikeRepository.java
  src/main/java/kr/co/souso/souso/domain/user/domain/User.java
Labels: feature, fix

#163 merge(#162): location 칼럼 추가 및 수정사항 반영
  src/main/java/kr/co/souso/souso/domain/bookmark/domain/repository/FeedBookmarkRepository.java
  src/main/java/kr/co/souso/souso/domain/category/domain/repository/FeedCategoryRepository.java
  src/main/java/kr/co/souso/souso/domain/category/service/QueryFeedCategoryPagesService.java
  src/main/java/kr/co/souso/souso/domain/comment/domain/repository/CommentRepository.java
  src/main/java/kr/co/souso/souso/domain/comment/domain/repository/CommentRepositoryImpl.java
  src/main/java/kr/co/souso/souso/domain/comment/presentation/dto/response/CreateCommentResponse.java
  src/main/java/kr/co/souso/souso/domain/comment/presentation/dto/response/CreateReplyResponse.java
  src/main/java/kr/co/souso/souso/domain/comment/service/QueryCommentPagesService.java
  src/main/java/kr/co/souso/souso/domain/feed/domain/repository/FeedRepositoryImpl.java
  src/main/java/kr/co/souso/souso/domain/feed/presentation/dto/response/CreateFeedResponse.java
  src/main/java/kr/co/souso/souso/domain/feed/service/QueryFeedDetailsService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/QueryFeedPagesService.java
  src/main/java/kr/co/souso/souso/domain/meeting/domain/repository/MeetingImageRepository.java
  src/main/java/kr/co/souso/souso/domain/user/domain/User.java
  src/main/java/kr/co/souso/souso/domain/user/domain/repository/vo/AuthorVO.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/response/AuthorResponse.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/response/QueryMyProfileResponse.java
  src/main/java/kr/co/souso/souso/domain/user/service/QueryMyProfileService.java
  src/main/java/kr/co/souso/souso/domain/user/service/UserSignUpService.java
Labels: feature, fix

#165 merge(#164): 내 동네 수정 API
  src/main/java/kr/co/souso/souso/domain/user/domain/User.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/UserController.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/request/UpdateMyLocationRequest.java
  src/main/java/kr/co/souso/souso/domain/user/service/UpdateMyLocationService.java
  src/main/java/kr/co/souso/souso/domain/user/service/UserAuthCodeService.java
  src/main/java/kr/co/souso/souso/global/security/SecurityConfig.java
Labels: feature

#172 merge(#170): sonarcloud 연동
  .github/workflows/Build.yml
  .github/workflows/CI.yml
  build.gradle
Labels: feature

#174 merge(#173): Convention 통일
  src/main/java/kr/co/souso/souso/domain/auth/service/UserSignInService.java
  src/main/java/kr/co/souso/souso/domain/comment/service/UpdateCommentService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/QueryFeedDetailsService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/UpdateFeedService.java
  src/main/java/kr/co/souso/souso/domain/user/service/UpdatePasswordService.java
  src/main/java/kr/co/souso/souso/domain/user/service/UpdateUserInfoService.java
  src/main/java/kr/co/souso/souso/domain/user/service/UserLogoutService.java
  src/main/java/kr/co/souso/souso/domain/user/service/UserSignUpService.java
  src/main/java/kr/co/souso/souso/domain/user/service/UserWithdrawalService.java
  src/main/java/kr/co/souso/souso/global/utils/code/PagingSupportUtil.java
Labels: chore

#177 merge(#176): 자동화 배포
  .github/workflows/Build.yml
  .github/workflows/CD.yml
  Dockerfile
  docker.aws.json
  src/main/java/kr/co/souso/souso/domain/comment/domain/Comment.java
  src/main/java/kr/co/souso/souso/domain/comment/presentation/CommentController.java
  src/main/java/kr/co/souso/souso/domain/feed/presentation/FeedController.java
  src/main/java/kr/co/souso/souso/domain/feed/service/DeleteFeedService.java
  src/main/java/kr/co/souso/souso/domain/healthcheck/HealthCheckController.java
  src/main/java/kr/co/souso/souso/domain/meeting/domain/Meeting.java
  src/main/java/kr/co/souso/souso/global/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: feature, chore, fix

#181 merge(#180): infrastructure 패키지 네이밍 일관성 작업
  src/main/java/kr/co/souso/souso/domain/category/presentation/CategoryController.java
  src/main/java/kr/co/souso/souso/domain/feed/service/CreateFeedService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/UpdateFeedService.java
  src/main/java/kr/co/souso/souso/domain/image/service/UploadImageService.java
  src/main/java/kr/co/souso/souso/domain/meeting/service/CreateMeetingService.java
  src/main/java/kr/co/souso/souso/domain/user/service/UpdateUserInfoService.java
  src/main/java/kr/co/souso/souso/infrastructure/image/ImageService.java
  src/main/java/kr/co/souso/souso/infrastructure/image/s3/S3Service.java
  src/main/java/kr/co/souso/souso/infrastructure/sms/SmsService.java
  src/main/java/kr/co/souso/souso/infrastructure/sms/coolsms/CoolSmsService.java
Labels: fix

#182 merge(#179): 좋아요 수, 북마크 수, 댓글 수 관리 방식 변경
  src/main/java/kr/co/souso/souso/domain/comment/service/CreateCommentService.java
  src/main/java/kr/co/souso/souso/domain/comment/service/CreateReplyService.java
  src/main/java/kr/co/souso/souso/domain/comment/service/DeleteCommentService.java
  src/main/java/kr/co/souso/souso/domain/feed/domain/Feed.java
  src/main/java/kr/co/souso/souso/domain/feed/domain/repository/FeedRepositoryImpl.java
  src/main/java/kr/co/souso/souso/domain/feed/service/AddBookmarkService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/AddLikeService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/QueryFeedDetailsService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/SubBookmarkService.java
  src/main/java/kr/co/souso/souso/domain/feed/service/SubLikeService.java
Labels: fix

#184 merge(#183): 인기글 조회 오류 수정
  src/main/java/kr/co/souso/souso/domain/category/presentation/dto/response/QueryFeedCategoryDetailsResponse.java
  src/main/java/kr/co/souso/souso/domain/feed/domain/Feed.java
  src/main/java/kr/co/souso/souso/domain/feed/domain/repository/FeedRepositoryImpl.java
  src/main/java/kr/co/souso/souso/domain/feed/domain/repository/vo/FeedDetailsVO.java
  src/main/java/kr/co/souso/souso/domain/feed/presentation/dto/response/QueryFeedDetailsResponse.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/response/QueryMyBookmarksDetailsResponse.java
  src/main/java/kr/co/souso/souso/domain/user/presentation/dto/response/QueryMyFeedDetailsResponse.java
  src/main/java/kr/co/souso/souso/global/utils/code/PagingSupportUtil.java
  src/main/java/kr/co/souso/souso/global/utils/code/QueryDslSupportUtil.java
Labels: bug
